<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_lTAOICHkEfCERoyX9R9ziA" name="MonDiagramme" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_kfNM8Do-EfC53rJneDzihw" name="Pool1">
      <elements xmi:type="process:Lane" xmi:id="_xecw8DpGEfC53rJneDzihw" name="Etudiant" actor="__chTsDpZEfCbMuZErHeeeA">
        <elements xmi:type="process:Task" xmi:id="_qmFEkTo-EfC53rJneDzihw" name="DebutStage" outgoing="_qmMZUDo-EfC53rJneDzihw" incoming="_qmQqwDo-EfC53rJneDzihw" actor="__chTsDpZEfCbMuZErHeeeA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmFEkjo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmFEkzo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmFElDo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qmFElTo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qmFEljo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qmFElzo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qmFEmDo-EfC53rJneDzihw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qmFEmTo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_qmFEmjo-EfC53rJneDzihw">
            <targetForm xmi:type="expression:Expression" xmi:id="_YOGqQDqXEfCfZqubyYbZTg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_qmFEnDo-EfC53rJneDzihw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_qmFEnTo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_qmGSsDo-EfC53rJneDzihw" name="Démarrer1" outgoing="_qmNAZjo-EfC53rJneDzihw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmGSsTo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmGSsjo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmGSszo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_qmG5wzo-EfC53rJneDzihw" name="Fin1" incoming="_qmMZUDo-EfC53rJneDzihw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmG5xDo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmG5xTo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmG5xjo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_qmJ9Ezo-EfC53rJneDzihw" name="Choix Sujet" outgoing="_qmQDsDo-EfC53rJneDzihw" incoming="_qmR44Do-EfC53rJneDzihw" actor="__chTsDpZEfCbMuZErHeeeA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmJ9FDo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmJ9FTo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmJ9Fjo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_5o0LsDqFEfC8nPrQSXkqiA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_5o0LsTqFEfC8nPrQSXkqiA" name="sujet_choix" content="sujet_choix" type="TYPE_VARIABLE" returnType="com.company.model.SujetStage">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8PAK0DqFEfC8nPrQSXkqiA" name="sujet_choix" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.SujetStage"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_5o0LsjqFEfC8nPrQSXkqiA" name="newScript()" content="sujet_prop.find { it.titre == sujet_titre }" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.SujetStage">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_bZAqkDqYEfCfZqubyYbZTg" name="sujet_prop" multiple="true" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.SujetStage"/>
              <referencedElements xmi:type="process:ContractInput" xmi:id="_bZAqkTqYEfCfZqubyYbZTg" name="sujet_titre">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_bZAqkjqYEfCfZqubyYbZTg"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_5o0LszqFEfC8nPrQSXkqiA" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qmJ9Fzo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qmJ9GDo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qmJ9GTo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qmJ9Gjo-EfC53rJneDzihw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qmJ9Gzo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_qmJ9HDo-EfC53rJneDzihw" url="../API/bdm/businessData/com.company.model.SujetStage?p=0&amp;c=100">
            <targetForm xmi:type="expression:Expression" xmi:id="_gcl-YDqGEfC8nPrQSXkqiA" name="newForm" content="71846adf-2758-4fc6-aefb-bdfe961f42a9" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_qmJ9Hjo-EfC53rJneDzihw">
            <inputs xmi:type="process:ContractInput" xmi:id="_VfggkDqYEfCfZqubyYbZTg" name="sujet_titre">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_VfggkTqYEfCfZqubyYbZTg"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_qmJ9Hzo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_qmKkIDo-EfC53rJneDzihw" name="Porte4" outgoing="_qmQqwDo-EfC53rJneDzihw _qmQqyDo-EfC53rJneDzihw" incoming="_qmO1kDo-EfC53rJneDzihw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmKkITo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmKkIjo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmKkIzo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_qmLLMDo-EfC53rJneDzihw" name="Porte5" outgoing="_qmRR1To-EfC53rJneDzihw _qmR44Do-EfC53rJneDzihw" incoming="_qmNneDo-EfC53rJneDzihw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmLLMTo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmLLMjo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmLLMzo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_qmLyQzo-EfC53rJneDzihw" name="Proposition de sujet" outgoing="_qmSf9To-EfC53rJneDzihw" incoming="_qmRR1To-EfC53rJneDzihw" actor="__chTsDpZEfCbMuZErHeeeA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmLyRDo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmLyRTo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmLyRjo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_9MdmtDqHEfC8nPrQSXkqiA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_9MdmtTqHEfC8nPrQSXkqiA" name="sujet_choix" content="sujet_choix" type="TYPE_VARIABLE" returnType="com.company.model.SujetStage">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_9MdmtjqHEfC8nPrQSXkqiA" name="sujet_choix" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.SujetStage"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_9MdmtzqHEfC8nPrQSXkqiA" name="sujet_choixInput.titre" content="sujet_choixInput?.titre" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_9MdmuDqHEfC8nPrQSXkqiA" name="sujet_choixInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_9MdmuTqHEfC8nPrQSXkqiA" type="JAVA_METHOD" expression="setTitre">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_9MdmujqHEfC8nPrQSXkqiA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_9MdmuzqHEfC8nPrQSXkqiA" name="sujet_choix" content="sujet_choix" type="TYPE_VARIABLE" returnType="com.company.model.SujetStage">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_9MdmvDqHEfC8nPrQSXkqiA" name="sujet_choix" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.SujetStage"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_9MdmvTqHEfC8nPrQSXkqiA" name="sujet_choixInput.description" content="sujet_choixInput?.description" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_9MdmvjqHEfC8nPrQSXkqiA" name="sujet_choixInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_9MdmvzqHEfC8nPrQSXkqiA" type="JAVA_METHOD" expression="setDescription">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_DlCSUDqIEfC8nPrQSXkqiA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DlCSUTqIEfC8nPrQSXkqiA" name="sujet_choix" content="sujet_choix" type="TYPE_VARIABLE" returnType="com.company.model.SujetStage">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_EQYVYDqIEfC8nPrQSXkqiA" name="sujet_choix" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.SujetStage"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DlCSUjqIEfC8nPrQSXkqiA" name="newScript()" content="true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean"/>
            <operator xmi:type="expression:Operator" xmi:id="_DlCSUzqIEfC8nPrQSXkqiA" type="JAVA_METHOD" expression="setProposeParEtudiant">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_LKUosDqIEfC8nPrQSXkqiA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_LKUosTqIEfC8nPrQSXkqiA" name="sujet_choix" content="sujet_choix" type="TYPE_VARIABLE" returnType="com.company.model.SujetStage">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_MsEIQDqIEfC8nPrQSXkqiA" name="sujet_choix" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.SujetStage"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_LKUosjqIEfC8nPrQSXkqiA" name="newScript()" content="false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean"/>
            <operator xmi:type="expression:Operator" xmi:id="_LKUoszqIEfC8nPrQSXkqiA" type="JAVA_METHOD" expression="setValide">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qmLyRzo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qmLySDo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qmLySTo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qmLySjo-EfC53rJneDzihw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qmLySzo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_qmLyTDo-EfC53rJneDzihw">
            <targetForm xmi:type="expression:Expression" xmi:id="_YOGqQTqXEfCfZqubyYbZTg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_qmLyTjo-EfC53rJneDzihw">
            <inputs xmi:type="process:ContractInput" xmi:id="_9MdmsDqHEfC8nPrQSXkqiA" name="sujet_choixInput" type="COMPLEX" dataReference="sujet_choix" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_9MdmsTqHEfC8nPrQSXkqiA" name="titre" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_9MdmsjqHEfC8nPrQSXkqiA" name="description" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_9MdmszqHEfC8nPrQSXkqiA" expression="sujet_choixInput?.titre != null" errorMessage="titre is mandatory for SujetStage" name="mandatory_sujet_choixInput_titre">
              <inputNames>sujet_choixInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_qmLyTzo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_PbCaIDo_EfC53rJneDzihw" name="MajDate" outgoing="_qmPcpjo-EfC53rJneDzihw" incoming="_qmQqyDo-EfC53rJneDzihw" actor="__chTsDpZEfCbMuZErHeeeA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmJWBDo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmJWBTo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmJWBjo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qmJWBzo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qmJWCDo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qmJWCTo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qmJWCjo-EfC53rJneDzihw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qmJWCzo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PbDBOTo_EfC53rJneDzihw">
            <targetForm xmi:type="expression:Expression" xmi:id="_YOGqQjqXEfCfZqubyYbZTg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PbDBODo_EfC53rJneDzihw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PbDBOzo_EfC53rJneDzihw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_TmHGEDqEEfC8nPrQSXkqiA" name="choisir type de sujet" outgoing="_qmNneDo-EfC53rJneDzihw" incoming="_QrlOoDqEEfC8nPrQSXkqiA _qmOOjjo-EfC53rJneDzihw" actor="__chTsDpZEfCbMuZErHeeeA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QrfIATqEEfC8nPrQSXkqiA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QrfIADqEEfC8nPrQSXkqiA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QrfIAjqEEfC8nPrQSXkqiA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_weWcsDqEEfC8nPrQSXkqiA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_weWcsTqEEfC8nPrQSXkqiA" name="choix_proposition" content="choix_proposition" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_xlYWMDqEEfC8nPrQSXkqiA" documentation="voulez vous choisir votre sujet parmis une liste ?" name="choix_proposition" dataType="_lTAOTCHkEfCERoyX9R9ziA"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_weWcsjqEEfC8nPrQSXkqiA" name="choix_proposition" content="choix_proposition" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yGQ1sDqEEfC8nPrQSXkqiA" name="choix_proposition" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_yGQ1sTqEEfC8nPrQSXkqiA"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_weWcszqEEfC8nPrQSXkqiA" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QrfIAzqEEfC8nPrQSXkqiA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QrfIBDqEEfC8nPrQSXkqiA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QrfIBTqEEfC8nPrQSXkqiA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QrfIBzqEEfC8nPrQSXkqiA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QrfIBjqEEfC8nPrQSXkqiA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_TmHGGjqEEfC8nPrQSXkqiA">
            <targetForm xmi:type="expression:Expression" xmi:id="_YOGqQzqXEfCfZqubyYbZTg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_TmHGGTqEEfC8nPrQSXkqiA">
            <inputs xmi:type="process:ContractInput" xmi:id="_oYyq0DqEEfC8nPrQSXkqiA" name="choix_proposition" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_oYyq0TqEEfC8nPrQSXkqiA"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_TmHGHDqEEfC8nPrQSXkqiA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_IoIpUDpHEfC53rJneDzihw" name="Responsable" actor="_Cax0kDpaEfCbMuZErHeeeA">
        <elements xmi:type="process:Task" xmi:id="_qmHg0Do-EfC53rJneDzihw" name="Publication de sujet de stage" outgoing="_QrlOoDqEEfC8nPrQSXkqiA" incoming="_qmNAZjo-EfC53rJneDzihw" actor="_Cax0kDpaEfCbMuZErHeeeA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmHg0To-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmHg0jo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmHg0zo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_nXGKADqUEfCfZqubyYbZTg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_nXGKATqUEfCfZqubyYbZTg" name="sujet_prop" content="sujet_prop" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nXGKAjqUEfCfZqubyYbZTg" name="sujet_prop" multiple="true" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.SujetStage"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_nXGKAzqUEfCfZqubyYbZTg" name="sujet_propInput" content="def sujetStageList = []&#xD;&#xA;&#xD;&#xA;// Pour chaque sujet saisi par l'utilisateur&#xD;&#xA;sujet_propInput.each { currentSujetStageInput ->&#xD;&#xA;    def sujetStageVar = new com.company.model.SujetStage()&#xD;&#xA;    sujetStageVar.titre = currentSujetStageInput.titre&#xD;&#xA;    sujetStageVar.description = currentSujetStageInput.description&#xD;&#xA;    sujetStageList.add(sujetStageVar)&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;return sujetStageList" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_NP9sQDqYEfCfZqubyYbZTg" name="sujet_propInput" type="COMPLEX" multiple="true" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_nXGKBjqUEfCfZqubyYbZTg" type="ASSIGNMENT" expression="addAll">
              <inputTypes>java.util.Collection</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qmHg1Do-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qmHg1To-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qmHg1jo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qmHg1zo-EfC53rJneDzihw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qmHg2Do-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_qmHg2To-EfC53rJneDzihw">
            <targetForm xmi:type="expression:Expression" xmi:id="_YOGqRDqXEfCfZqubyYbZTg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_qmHg2zo-EfC53rJneDzihw">
            <inputs xmi:type="process:ContractInput" xmi:id="_nXFi8DqUEfCfZqubyYbZTg" name="sujet_propInput" type="COMPLEX" multiple="true" dataReference="sujet_prop" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_nXFi8TqUEfCfZqubyYbZTg" name="persistenceId_string" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_nXFi8jqUEfCfZqubyYbZTg" name="titre" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_nXFi8zqUEfCfZqubyYbZTg" name="description" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_nXFi9DqUEfCfZqubyYbZTg" expression="sujet_propInput?.titre.flatten().every{it!=null}" errorMessage="titre is mandatory for SujetStage" name="mandatory_sujet_propInput_titre">
              <inputNames>sujet_propInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_qmHg3Do-EfC53rJneDzihw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_qmIu8zo-EfC53rJneDzihw" name="Validation du sujet" outgoing="_qmO1mTo-EfC53rJneDzihw" incoming="_qmQDsDo-EfC53rJneDzihw _qmSf9To-EfC53rJneDzihw" actor="_Cax0kDpaEfCbMuZErHeeeA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmIu9Do-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmIu9To-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmIu9jo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qmIu9zo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qmIu-Do-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qmIu-To-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qmIu-jo-EfC53rJneDzihw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qmIu-zo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_qmIu_Do-EfC53rJneDzihw">
            <targetForm xmi:type="expression:Expression" xmi:id="_YOGqRTqXEfCfZqubyYbZTg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_qmIu_jo-EfC53rJneDzihw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_qmIu_zo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_qmIH4Do-EfC53rJneDzihw" name="Porte3" outgoing="_qmOOhjo-EfC53rJneDzihw _qmOOjjo-EfC53rJneDzihw" incoming="_qmO1mTo-EfC53rJneDzihw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmIH4To-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmIH4jo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmIH4zo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_qmLLODo-EfC53rJneDzihw" name="Signature Responsable" outgoing="_qmR46To-EfC53rJneDzihw" incoming="_qmNncDo-EfC53rJneDzihw" actor="_Cax0kDpaEfCbMuZErHeeeA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmLLOTo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmLLOjo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmLLOzo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qmLLPDo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qmLLPTo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qmLLPjo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qmLLPzo-EfC53rJneDzihw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qmLLQDo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_qmLLQTo-EfC53rJneDzihw">
            <targetForm xmi:type="expression:Expression" xmi:id="_YOGqRjqXEfCfZqubyYbZTg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_qmLLQzo-EfC53rJneDzihw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_qmLLRDo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_3_eN8DpGEfC53rJneDzihw" name="Referent" actor="_DMT_MDpaEfCbMuZErHeeeA">
        <elements xmi:type="process:Task" xmi:id="_qmGSuDo-EfC53rJneDzihw" name="Signature encadrant" outgoing="_qmNncDo-EfC53rJneDzihw" incoming="_qmOOhjo-EfC53rJneDzihw _qmPcpjo-EfC53rJneDzihw" actor="_DMT_MDpaEfCbMuZErHeeeA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmGSuTo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmGSujo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmGSuzo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qmGSvDo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qmGSvTo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qmGSvjo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qmGSvzo-EfC53rJneDzihw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qmGSwDo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_qmGSwTo-EfC53rJneDzihw">
            <targetForm xmi:type="expression:Expression" xmi:id="_YOGqRzqXEfCfZqubyYbZTg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_qmGSwzo-EfC53rJneDzihw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_qmGSxDo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_K2glYDpHEfC53rJneDzihw" name="Doyen" actor="_D2uOIDpaEfCbMuZErHeeeA">
        <elements xmi:type="process:Task" xmi:id="_qmIH6Do-EfC53rJneDzihw" name="SignatureDoyen" outgoing="_qmO1kDo-EfC53rJneDzihw" incoming="_qmR46To-EfC53rJneDzihw" actor="_D2uOIDpaEfCbMuZErHeeeA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qmIH6To-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qmIH6jo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qmIH6zo-EfC53rJneDzihw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qmIH7Do-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qmIH7To-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qmIH7jo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qmIH7zo-EfC53rJneDzihw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qmIH8Do-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_qmIH8To-EfC53rJneDzihw">
            <targetForm xmi:type="expression:Expression" xmi:id="_YOGqSDqXEfCfZqubyYbZTg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_qmIH8zo-EfC53rJneDzihw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_qmIH9Do-EfC53rJneDzihw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Vl1CcDqBEfC8nPrQSXkqiA" name="stage" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.Stage">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Vl1CcTqBEfC8nPrQSXkqiA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_WmU2IDqBEfC8nPrQSXkqiA" name="convention" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.Convention">
        <defaultValue xmi:type="expression:Expression" xmi:id="_WmU2ITqBEfC8nPrQSXkqiA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_NikhMDqCEfC8nPrQSXkqiA" name="sujet_choix" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.SujetStage">
        <defaultValue xmi:type="expression:Expression" xmi:id="_NikhMTqCEfC8nPrQSXkqiA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_u5x9gDqCEfC8nPrQSXkqiA" name="sujet_prop" multiple="true" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.SujetStage">
        <defaultValue xmi:type="expression:Expression" xmi:id="_u5x9gTqCEfC8nPrQSXkqiA" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_vQzrgDqEEfC8nPrQSXkqiA" documentation="voulez vous choisir votre sujet parmis une liste ?" name="choix_proposition" dataType="_lTAOTCHkEfCERoyX9R9ziA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_vQzrgTqEEfC8nPrQSXkqiA" content="" returnType="java.lang.Boolean"/>
      </data>
      <connectors xmi:type="process:Connector" xmi:id="_pix5EDqBEfC8nPrQSXkqiA" name="init stage et convention" definitionId="scripting-groovy-script" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.0.1">
        <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_pix5ETqBEfC8nPrQSXkqiA" definitionId="scripting-groovy-script" version="1.0.1" modelVersion="8">
          <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pix5EjqBEfC8nPrQSXkqiA" key="script">
            <expression xmi:type="expression:Expression" xmi:id="_pix5EzqBEfC8nPrQSXkqiA" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
          </parameters>
          <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pix5FDqBEfC8nPrQSXkqiA" key="variables">
            <expression xmi:type="expression:Expression" xmi:id="_pix5FTqBEfC8nPrQSXkqiA" returnType="java.util.List" returnTypeFixed="true"/>
          </parameters>
          <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_pix5FjqBEfC8nPrQSXkqiA" key="fakeScriptExpression">
            <expression xmi:type="expression:Expression" xmi:id="_pix5FzqBEfC8nPrQSXkqiA" name="newScript()" content="// Récupère le nom de l'utilisateur connecté&#xD;&#xA;def username = 'walter.bates'&#xD;&#xA;&#xD;&#xA;// Création de l'objet Stage&#xD;&#xA;def s = new com.company.model.Stage()&#xD;&#xA;s.etu_nom = username&#xD;&#xA;s.sujet = null&#xD;&#xA;s.dateDebut = null&#xD;&#xA;s.dateFin = null&#xD;&#xA;&#xD;&#xA;// Création de l'objet Convention&#xD;&#xA;def c = new com.company.model.Convention()&#xD;&#xA;c.signatureEtudiant = false&#xD;&#xA;c.signatureReferent = false&#xD;&#xA;c.signatureResponsable = false&#xD;&#xA;c.signatureDoyen = false&#xD;&#xA;c.referent_nom = 'anthony.nichols'&#xD;&#xA;c.stage = s&#xD;&#xA;&#xD;&#xA;// Retourne les deux objets dans une liste&#xD;&#xA;return [s, c]&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object" returnTypeFixed="true"/>
          </parameters>
        </configuration>
        <outputs xmi:type="expression:Operation" xmi:id="_pix5GTqBEfC8nPrQSXkqiA">
          <leftOperand xmi:type="expression:Expression" xmi:id="_pix5GjqBEfC8nPrQSXkqiA" name="stage" content="stage" type="TYPE_VARIABLE" returnType="com.company.model.Stage">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pix5GzqBEfC8nPrQSXkqiA" name="stage" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.Stage"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_pix5HDqBEfC8nPrQSXkqiA" name="newScript()" content="return connectorOutput[0]" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Stage"/>
          <operator xmi:type="expression:Operator" xmi:id="_pix5HTqBEfC8nPrQSXkqiA" type="ASSIGNMENT"/>
        </outputs>
        <outputs xmi:type="expression:Operation" xmi:id="_pix5HjqBEfC8nPrQSXkqiA">
          <leftOperand xmi:type="expression:Expression" xmi:id="_pix5HzqBEfC8nPrQSXkqiA" name="convention" content="convention" type="TYPE_VARIABLE" returnType="com.company.model.Convention">
            <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pix5IDqBEfC8nPrQSXkqiA" name="convention" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.Convention"/>
          </leftOperand>
          <rightOperand xmi:type="expression:Expression" xmi:id="_pix5ITqBEfC8nPrQSXkqiA" name="newScript()" content="return connectorOutput[1]" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Convention"/>
          <operator xmi:type="expression:Operator" xmi:id="_pix5IjqBEfC8nPrQSXkqiA" type="ASSIGNMENT"/>
        </outputs>
      </connectors>
      <formMapping xmi:type="process:FormMapping" xmi:id="_o2AOHzo-EfC53rJneDzihw">
        <targetForm xmi:type="expression:Expression" xmi:id="_YOGqSTqXEfCfZqubyYbZTg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_o2AOITo-EfC53rJneDzihw">
        <targetForm xmi:type="expression:Expression" xmi:id="_o2AOIjo-EfC53rJneDzihw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmMZUDo-EfC53rJneDzihw" target="_qmG5wzo-EfC53rJneDzihw" source="_qmFEkTo-EfC53rJneDzihw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmMZUTo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmMZUjo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmNAZjo-EfC53rJneDzihw" target="_qmHg0Do-EfC53rJneDzihw" source="_qmGSsDo-EfC53rJneDzihw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmNAZzo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmNAaDo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmNncDo-EfC53rJneDzihw" target="_qmLLODo-EfC53rJneDzihw" source="_qmGSuDo-EfC53rJneDzihw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmNncTo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmNncjo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmNneDo-EfC53rJneDzihw" target="_qmLLMDo-EfC53rJneDzihw" source="_TmHGEDqEEfC8nPrQSXkqiA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmNneTo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmNnejo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmOOhjo-EfC53rJneDzihw" name="SujetValidé" target="_qmGSuDo-EfC53rJneDzihw" source="_qmIH4Do-EfC53rJneDzihw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmOOhzo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmOOiDo-EfC53rJneDzihw" name="newScript()" content="sujet_choix.valide" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ilItUDqIEfC8nPrQSXkqiA" name="sujet_choix" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.SujetStage"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmOOjjo-EfC53rJneDzihw" target="_TmHGEDqEEfC8nPrQSXkqiA" source="_qmIH4Do-EfC53rJneDzihw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmOOjzo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmOOkDo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmO1kDo-EfC53rJneDzihw" target="_qmKkIDo-EfC53rJneDzihw" source="_qmIH6Do-EfC53rJneDzihw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmO1kTo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmO1kjo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmO1mTo-EfC53rJneDzihw" target="_qmIH4Do-EfC53rJneDzihw" source="_qmIu8zo-EfC53rJneDzihw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmO1mjo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmO1mzo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmPcpjo-EfC53rJneDzihw" target="_qmGSuDo-EfC53rJneDzihw" source="_PbCaIDo_EfC53rJneDzihw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmPcpzo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmPcqDo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmQDsDo-EfC53rJneDzihw" target="_qmIu8zo-EfC53rJneDzihw" source="_qmJ9Ezo-EfC53rJneDzihw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmQDsTo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmQDsjo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmQqwDo-EfC53rJneDzihw" name="StageAccepté" target="_qmFEkTo-EfC53rJneDzihw" source="_qmKkIDo-EfC53rJneDzihw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmQqwTo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmQqwjo-EfC53rJneDzihw" name="newScript()" content="convention.signatureEtudiant &amp;&amp;&#xD;&#xA;convention.signatureEncadrant &amp;&amp;&#xD;&#xA;convention.signatureResponsable &amp;&amp;&#xD;&#xA;convention.signatureDoyen &amp;&amp;&#xD;&#xA;convention.stage.dateDebut.isAfter(java.time.LocalDate.now())" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_fw318DqIEfC8nPrQSXkqiA" name="convention" dataType="_lTAOVCHkEfCERoyX9R9ziA" className="com.company.model.Convention"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmQqyDo-EfC53rJneDzihw" name="ProblèmeDossier" target="_PbCaIDo_EfC53rJneDzihw" source="_qmKkIDo-EfC53rJneDzihw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmQqyTo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmQqyjo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmRR1To-EfC53rJneDzihw" target="_qmLyQzo-EfC53rJneDzihw" source="_qmLLMDo-EfC53rJneDzihw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmRR1jo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmRR1zo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmR44Do-EfC53rJneDzihw" target="_qmJ9Ezo-EfC53rJneDzihw" source="_qmLLMDo-EfC53rJneDzihw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmR44To-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmR44jo-EfC53rJneDzihw" name="newScript()" content="choix_proposition" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_ffnOMDqFEfC8nPrQSXkqiA" documentation="voulez vous choisir votre sujet parmis une liste ?" name="choix_proposition" dataType="_lTAOTCHkEfCERoyX9R9ziA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmR46To-EfC53rJneDzihw" target="_qmIH6Do-EfC53rJneDzihw" source="_qmLLODo-EfC53rJneDzihw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmR46jo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmR46zo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qmSf9To-EfC53rJneDzihw" target="_qmIu8zo-EfC53rJneDzihw" source="_qmLyQzo-EfC53rJneDzihw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qmSf9jo-EfC53rJneDzihw"/>
        <condition xmi:type="expression:Expression" xmi:id="_qmSf9zo-EfC53rJneDzihw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QrlOoDqEEfC8nPrQSXkqiA" target="_TmHGEDqEEfC8nPrQSXkqiA" source="_qmHg0Do-EfC53rJneDzihw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QrlOoTqEEfC8nPrQSXkqiA"/>
        <condition xmi:type="expression:Expression" xmi:id="_QrlOojqEEfC8nPrQSXkqiA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_qmFEkDo-EfC53rJneDzihw" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor"/>
      <actors xmi:type="process:Actor" xmi:id="__chTsDpZEfCbMuZErHeeeA" name="EtudiantActor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_Cax0kDpaEfCbMuZErHeeeA" name="ResponsableActor"/>
      <actors xmi:type="process:Actor" xmi:id="_DMT_MDpaEfCbMuZErHeeeA" name="ReferentActor"/>
      <actors xmi:type="process:Actor" xmi:id="_D2uOIDpaEfCbMuZErHeeeA" name="DoyenActor"/>
      <contract xmi:type="process:Contract" xmi:id="_o2AOIzo-EfC53rJneDzihw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_o2AOEDo-EfC53rJneDzihw">
        <name xmi:type="expression:Expression" xmi:id="_o2AOETo-EfC53rJneDzihw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_o2AOEjo-EfC53rJneDzihw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_o2AOEzo-EfC53rJneDzihw">
        <name xmi:type="expression:Expression" xmi:id="_o2AOFDo-EfC53rJneDzihw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_o2AOFTo-EfC53rJneDzihw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_o2AOFjo-EfC53rJneDzihw">
        <name xmi:type="expression:Expression" xmi:id="_o2AOFzo-EfC53rJneDzihw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_o2AOGDo-EfC53rJneDzihw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_o2AOGTo-EfC53rJneDzihw">
        <name xmi:type="expression:Expression" xmi:id="_o2AOGjo-EfC53rJneDzihw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_o2AOGzo-EfC53rJneDzihw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_o2AOHDo-EfC53rJneDzihw">
        <name xmi:type="expression:Expression" xmi:id="_o2AOHTo-EfC53rJneDzihw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_o2AOHjo-EfC53rJneDzihw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_lTAOTCHkEfCERoyX9R9ziA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_lTAOTSHkEfCERoyX9R9ziA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_lTAOTiHkEfCERoyX9R9ziA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_lTAOTyHkEfCERoyX9R9ziA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_lTAOUCHkEfCERoyX9R9ziA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_lTAOUSHkEfCERoyX9R9ziA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_lTAOUiHkEfCERoyX9R9ziA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_lTAOUyHkEfCERoyX9R9ziA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_lTAOVCHkEfCERoyX9R9ziA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_lTA1MCHkEfCERoyX9R9ziA" type="Process" element="_lTAOICHkEfCERoyX9R9ziA" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_o2BcMDo-EfC53rJneDzihw" type="2007" element="_kfNM8Do-EfC53rJneDzihw">
      <children xmi:type="notation:DecorationNode" xmi:id="_o2BcNTo-EfC53rJneDzihw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_o2BcNjo-EfC53rJneDzihw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_xeemIDpGEfC53rJneDzihw" type="3007" element="_xecw8DpGEfC53rJneDzihw">
          <children xmi:type="notation:DecorationNode" xmi:id="_xefNMDpGEfC53rJneDzihw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_xefNMTpGEfC53rJneDzihw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_qmFroDo-EfC53rJneDzihw" type="3005" element="_qmFEkTo-EfC53rJneDzihw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmFroTo-EfC53rJneDzihw" type="5005" element="_qmFEkTo-EfC53rJneDzihw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmFrojo-EfC53rJneDzihw" x="899" y="46" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qmGStDo-EfC53rJneDzihw" type="3002" element="_qmGSsDo-EfC53rJneDzihw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmGStTo-EfC53rJneDzihw" type="5024" element="_qmGSsDo-EfC53rJneDzihw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qmGStjo-EfC53rJneDzihw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmGStzo-EfC53rJneDzihw" x="129" y="55"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qmG5xzo-EfC53rJneDzihw" type="3003" element="_qmG5wzo-EfC53rJneDzihw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmG5yDo-EfC53rJneDzihw" type="5025" element="_qmG5wzo-EfC53rJneDzihw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qmG5yTo-EfC53rJneDzihw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmG5yjo-EfC53rJneDzihw" x="1049" y="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qmJ9IDo-EfC53rJneDzihw" type="3005" element="_qmJ9Ezo-EfC53rJneDzihw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmJ9ITo-EfC53rJneDzihw" type="5005" element="_qmJ9Ezo-EfC53rJneDzihw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmJ9Ijo-EfC53rJneDzihw" x="424" y="94" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qmKkJDo-EfC53rJneDzihw" type="3008" element="_qmKkIDo-EfC53rJneDzihw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmKkJTo-EfC53rJneDzihw" type="5026" element="_qmKkIDo-EfC53rJneDzihw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qmKkJjo-EfC53rJneDzihw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmKkJzo-EfC53rJneDzihw" x="970" y="122"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qmLLNDo-EfC53rJneDzihw" type="3008" element="_qmLLMDo-EfC53rJneDzihw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmLLNTo-EfC53rJneDzihw" type="5026" element="_qmLLMDo-EfC53rJneDzihw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qmLLNjo-EfC53rJneDzihw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmLLNzo-EfC53rJneDzihw" x="251" y="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qmLyUDo-EfC53rJneDzihw" type="3005" element="_qmLyQzo-EfC53rJneDzihw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmLyUTo-EfC53rJneDzihw" type="5005" element="_qmLyQzo-EfC53rJneDzihw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmLyUjo-EfC53rJneDzihw" x="419" y="19" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_PbDBPDo_EfC53rJneDzihw" type="3005" element="_PbCaIDo_EfC53rJneDzihw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PbEPUDo_EfC53rJneDzihw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PbDBPTo_EfC53rJneDzihw" x="706" y="46" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TmHGHTqEEfC8nPrQSXkqiA" type="3005" element="_TmHGEDqEEfC8nPrQSXkqiA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TmHtIDqEEfC8nPrQSXkqiA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TmHGHjqEEfC8nPrQSXkqiA" x="161" y="142" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_xeemITpGEfC53rJneDzihw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_xeemIjpGEfC53rJneDzihw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_xeemIzpGEfC53rJneDzihw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_xefNMjpGEfC53rJneDzihw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xeemJDpGEfC53rJneDzihw" x="48" y="10" width="1093" height="218"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_3_e1ADpGEfC53rJneDzihw" type="3007" element="_3_eN8DpGEfC53rJneDzihw">
          <children xmi:type="notation:DecorationNode" xmi:id="_3_fcEDpGEfC53rJneDzihw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_3_fcETpGEfC53rJneDzihw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_qmG5wDo-EfC53rJneDzihw" type="3005" element="_qmGSuDo-EfC53rJneDzihw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmG5wTo-EfC53rJneDzihw" type="5005" element="_qmGSuDo-EfC53rJneDzihw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmG5wjo-EfC53rJneDzihw" x="707" y="27" width="126" height="63"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_3_e1ATpGEfC53rJneDzihw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_3_e1AjpGEfC53rJneDzihw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_3_e1AzpGEfC53rJneDzihw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_3_fcEjpGEfC53rJneDzihw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3_e1BDpGEfC53rJneDzihw" x="48" y="518" width="1093" height="118"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_IoIpUTpHEfC53rJneDzihw" type="3007" element="_IoIpUDpHEfC53rJneDzihw">
          <children xmi:type="notation:DecorationNode" xmi:id="_IoJQYDpHEfC53rJneDzihw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_IoJQYTpHEfC53rJneDzihw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_qmHg3To-EfC53rJneDzihw" type="3005" element="_qmHg0Do-EfC53rJneDzihw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmHg3jo-EfC53rJneDzihw" type="5005" element="_qmHg0Do-EfC53rJneDzihw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmHg3zo-EfC53rJneDzihw" x="134" y="21" width="152" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qmJWADo-EfC53rJneDzihw" type="3005" element="_qmIu8zo-EfC53rJneDzihw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmJWATo-EfC53rJneDzihw" type="5005" element="_qmIu8zo-EfC53rJneDzihw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmJWAjo-EfC53rJneDzihw" x="422" y="29" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qmIH5Do-EfC53rJneDzihw" type="3008" element="_qmIH4Do-EfC53rJneDzihw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmIH5To-EfC53rJneDzihw" type="5026" element="_qmIH4Do-EfC53rJneDzihw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qmIH5jo-EfC53rJneDzihw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmIH5zo-EfC53rJneDzihw" x="631" y="46"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qmLyQDo-EfC53rJneDzihw" type="3005" element="_qmLLODo-EfC53rJneDzihw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmLyQTo-EfC53rJneDzihw" type="5005" element="_qmLLODo-EfC53rJneDzihw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmLyQjo-EfC53rJneDzihw" x="775" y="28" width="125" height="62"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_IoIpUjpHEfC53rJneDzihw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_IoIpUzpHEfC53rJneDzihw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_IoIpVDpHEfC53rJneDzihw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_IoJQYjpHEfC53rJneDzihw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IoIpVTpHEfC53rJneDzihw" x="48" y="218" width="1093" height="133"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_K2glYTpHEfC53rJneDzihw" type="3007" element="_K2glYDpHEfC53rJneDzihw">
          <children xmi:type="notation:DecorationNode" xmi:id="_K2glZjpHEfC53rJneDzihw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_K2glZzpHEfC53rJneDzihw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_qmIu8Do-EfC53rJneDzihw" type="3005" element="_qmIH6Do-EfC53rJneDzihw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qmIu8To-EfC53rJneDzihw" type="5005" element="_qmIH6Do-EfC53rJneDzihw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qmIu8jo-EfC53rJneDzihw" x="886" y="19" width="126" height="63"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_K2glYjpHEfC53rJneDzihw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_K2glYzpHEfC53rJneDzihw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_K2glZDpHEfC53rJneDzihw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_K2hMcDpHEfC53rJneDzihw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_K2glZTpHEfC53rJneDzihw" x="48" y="469" width="1145" height="110"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_o2BcMTo-EfC53rJneDzihw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_o2BcMjo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_o2BcMzo-EfC53rJneDzihw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_o2BcNzo-EfC53rJneDzihw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_o2BcNDo-EfC53rJneDzihw" width="1168" height="518"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_lTA1SCHkEfCERoyX9R9ziA"/>
    <edges xmi:type="notation:Connector" xmi:id="_qmNAYDo-EfC53rJneDzihw" type="4001" element="_qmMZUDo-EfC53rJneDzihw" source="_qmFroDo-EfC53rJneDzihw" target="_qmG5xzo-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmNAYTo-EfC53rJneDzihw" type="6001" element="_qmMZUDo-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmNAYjo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmNAYzo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmNAZDo-EfC53rJneDzihw" points="[-75, -4, 73, -2]$[-152, -13, -4, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmNAZTo-EfC53rJneDzihw" id="(1.0,0.56)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmNAaTo-EfC53rJneDzihw" type="4001" element="_qmNAZjo-EfC53rJneDzihw" source="_qmGStDo-EfC53rJneDzihw" target="_qmHg3To-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmNAajo-EfC53rJneDzihw" type="6001" element="_qmNAZjo-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmNAazo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmNAbDo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmNAbTo-EfC53rJneDzihw" points="[2, 14, -56, -282]$[2, 156, -56, -140]$[-2, 156, -60, -140]$[-2, 253, -60, -43]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmNnczo-EfC53rJneDzihw" type="4001" element="_qmNncDo-EfC53rJneDzihw" source="_qmG5wDo-EfC53rJneDzihw" target="_qmLyQDo-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmNndDo-EfC53rJneDzihw" type="6001" element="_qmNncDo-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmNndTo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmNndjo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmNndzo-EfC53rJneDzihw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmOOgDo-EfC53rJneDzihw" type="4001" element="_qmNneDo-EfC53rJneDzihw" source="_TmHGHTqEEfC8nPrQSXkqiA" target="_qmLLNDo-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmOOgTo-EfC53rJneDzihw" type="6001" element="_qmNneDo-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmOOgjo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmOOgzo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmOOhDo-EfC53rJneDzihw" points="[-12, -5, -62, 37]$[-12, -51, -62, -9]$[38, -51, -12, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmOOhTo-EfC53rJneDzihw" id="(0.61,0.1)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmOOiTo-EfC53rJneDzihw" type="4001" element="_qmOOhjo-EfC53rJneDzihw" source="_qmIH5Do-EfC53rJneDzihw" target="_qmG5wDo-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmOOijo-EfC53rJneDzihw" type="6001" element="_qmOOhjo-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmOOizo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmOOjDo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmOOjTo-EfC53rJneDzihw" points="[0, 22, -118, -102]$[0, 122, -118, -2]$[55, 122, -63, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmOOkTo-EfC53rJneDzihw" type="4001" element="_qmOOjjo-EfC53rJneDzihw" source="_qmIH5Do-EfC53rJneDzihw" target="_TmHGHTqEEfC8nPrQSXkqiA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmOOkjo-EfC53rJneDzihw" type="6001" element="_qmOOjjo-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmOOkzo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmOOlDo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmOOlTo-EfC53rJneDzihw" points="[-25, -31, 390, 104]$[-25, -138, 390, -3]$[-413, -138, 2, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmOOljo-EfC53rJneDzihw" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UTCqQDqUEfCfZqubyYbZTg" id="(0.98,0.42)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmO1kzo-EfC53rJneDzihw" type="4001" element="_qmO1kDo-EfC53rJneDzihw" source="_qmIu8Do-EfC53rJneDzihw" target="_qmKkJDo-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmO1lDo-EfC53rJneDzihw" type="6001" element="_qmO1kDo-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmO1lTo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmO1ljo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmO1lzo-EfC53rJneDzihw" points="[-20, -37, 1, 345]$[-20, -361, 1, 21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmO1mDo-EfC53rJneDzihw" id="(1.0,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmPcoDo-EfC53rJneDzihw" type="4001" element="_qmO1mTo-EfC53rJneDzihw" source="_qmJWADo-EfC53rJneDzihw" target="_qmIH5Do-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmPcoTo-EfC53rJneDzihw" type="6001" element="_qmO1mTo-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmPcojo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmPcozo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmPcpDo-EfC53rJneDzihw" points="[0, -9, -110, 3]$[91, -9, -19, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmPcpTo-EfC53rJneDzihw" id="(1.0,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmPcqTo-EfC53rJneDzihw" type="4001" element="_qmPcpjo-EfC53rJneDzihw" source="_PbDBPDo_EfC53rJneDzihw" target="_qmG5wDo-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmPcqjo-EfC53rJneDzihw" type="6001" element="_qmPcpjo-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmPcqzo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmPcrDo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmPcrTo-EfC53rJneDzihw" points="[-69, 21, 24, -377]$[-69, 370, 24, -28]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmPcrjo-EfC53rJneDzihw" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmPcrzo-EfC53rJneDzihw" id="(0.05,0.46)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmQDszo-EfC53rJneDzihw" type="4001" element="_qmQDsDo-EfC53rJneDzihw" source="_qmJ9IDo-EfC53rJneDzihw" target="_qmJWADo-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmQDtDo-EfC53rJneDzihw" type="6001" element="_qmQDsDo-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmQDtTo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmQDtjo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmQDtzo-EfC53rJneDzihw" points="[-46, 24, 43, -142]$[-46, 127, 43, -39]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmQDuDo-EfC53rJneDzihw" id="(1.0,0.52)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmQDuTo-EfC53rJneDzihw" id="(0.11,0.66)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmQqwzo-EfC53rJneDzihw" type="4001" element="_qmQqwDo-EfC53rJneDzihw" source="_qmKkJDo-EfC53rJneDzihw" target="_qmFroDo-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmQqxDo-EfC53rJneDzihw" type="6001" element="_qmQqwDo-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmQqxTo-EfC53rJneDzihw" x="-6" y="43"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmQqxjo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmQqxzo-EfC53rJneDzihw" points="[0, -21, 42, 51]$[0, -47, 42, 25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmRR0Do-EfC53rJneDzihw" type="4001" element="_qmQqyDo-EfC53rJneDzihw" source="_qmKkJDo-EfC53rJneDzihw" target="_PbDBPDo_EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmRR0To-EfC53rJneDzihw" type="6001" element="_qmQqyDo-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmRR0jo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmRR0zo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmRR1Do-EfC53rJneDzihw" points="[-21, 0, 214, 72]$[-141, 0, 94, 72]$[-141, -77, 94, -5]$[-185, -77, 50, -5]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmRR2Do-EfC53rJneDzihw" type="4001" element="_qmRR1To-EfC53rJneDzihw" source="_qmLLNDo-EfC53rJneDzihw" target="_qmLyUDo-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmRR2To-EfC53rJneDzihw" type="6001" element="_qmRR1To-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmRR2jo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmRR2zo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmRR3Do-EfC53rJneDzihw" points="[-18, -29, -170, 32]$[-18, -71, -170, -10]$[133, -71, -19, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmRR3To-EfC53rJneDzihw" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmRR3jo-EfC53rJneDzihw" id="(0.15833333333333333,0.65)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmR44zo-EfC53rJneDzihw" type="4001" element="_qmR44Do-EfC53rJneDzihw" source="_qmLLNDo-EfC53rJneDzihw" target="_qmJ9IDo-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmR45Do-EfC53rJneDzihw" type="6001" element="_qmR44Do-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmR45To-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmR45jo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmR45zo-EfC53rJneDzihw" points="[-3, -10, -183, -16]$[130, -10, -50, -16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmR46Do-EfC53rJneDzihw" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmSf8Do-EfC53rJneDzihw" type="4001" element="_qmR46To-EfC53rJneDzihw" source="_qmLyQDo-EfC53rJneDzihw" target="_qmIu8Do-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmSf8To-EfC53rJneDzihw" type="6001" element="_qmR46To-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmSf8jo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmSf8zo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmSf9Do-EfC53rJneDzihw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qmSf-Do-EfC53rJneDzihw" type="4001" element="_qmSf9To-EfC53rJneDzihw" source="_qmLyUDo-EfC53rJneDzihw" target="_qmJWADo-EfC53rJneDzihw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qmSf-To-EfC53rJneDzihw" type="6001" element="_qmSf9To-EfC53rJneDzihw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qmSf-jo-EfC53rJneDzihw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qmSf-zo-EfC53rJneDzihw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qmSf_Do-EfC53rJneDzihw" points="[-5, 39, 38, -289]$[-5, 168, 38, -160]$[-1, 168, 42, -160]$[-1, 298, 42, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qmSf_To-EfC53rJneDzihw" id="(1.0,0.35)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QrnD0DqEEfC8nPrQSXkqiA" type="4001" element="_QrlOoDqEEfC8nPrQSXkqiA" source="_qmHg3To-EfC53rJneDzihw" target="_TmHGHTqEEfC8nPrQSXkqiA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QrnD0zqEEfC8nPrQSXkqiA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QrnD1DqEEfC8nPrQSXkqiA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QrnD0TqEEfC8nPrQSXkqiA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QrnD0jqEEfC8nPrQSXkqiA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
